#!/usr/bin/env python3
"""Build the static (Pyodide) site.

``panel convert`` bundles a single script, so the embedded archive module and
the application are concatenated into one generated file first. The generated
file is disposable; ``static/app.py`` and ``static/_bundled_data.py`` are the
sources.

Usage:  python static/build.py [--out site]
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIC = ROOT / "static"
ARCHIVE = ROOT / "tests" / "fixtures" / "prerelease.zip"
EXPECTED_SHA256 = "07f0e8d9ac97a29ea376a0c7242de3124d2a08ad72aba0958d6575d94d35fa0b"

#: Pyodide-provided packages the app needs. gaiasupdate and astroquery are
#: deliberately absent: astroquery is not in the Pyodide distribution, so the
#: live fit cannot run in a browser.
REQUIREMENTS = [
    "numpy", "pandas", "astropy", "panel", "holoviews", "bokeh", "param", "platformdirs",
]


def embed_archive() -> Path:
    """Regenerate ``_bundled_data.py`` from the committed archive."""
    data = ARCHIVE.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(
            f"{ARCHIVE} has checksum {digest}, expected {EXPECTED_SHA256}. "
            "Refusing to embed an archive that is not the official one."
        )
    b64 = base64.b64encode(data).decode("ascii")
    lines = "\n".join(f'    "{b64[i:i + 76]}"' for i in range(0, len(b64), 76))
    out = STATIC / "_bundled_data.py"
    out.write_text(
        '"""The prerelease archive, embedded for the static build.\n\n'
        "A Pyodide page has no filesystem and no usable urllib, so the official\n"
        f"{len(data)}-byte archive travels with the application.\n"
        f"sha256 {digest}\n"
        "\nGenerated by static/build.py -- do not edit.\n"
        '"""\n\nimport base64\n\n'
        f"PRERELEASE_ZIP_B64 = (\n{lines}\n)\n\n\n"
        "def prerelease_zip_bytes() -> bytes:\n"
        '    """Decode the embedded archive."""\n'
        "    return base64.b64decode(PRERELEASE_ZIP_B64)\n"
    )
    return out


def _short_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def fingerprint(out: Path) -> None:
    """Give the worker script and its resources content-hashed names.

    GitHub Pages sends ``Cache-Control: max-age=600``. A reload revalidates
    ``index.html`` but serves still-fresh subresources from cache, so for ten
    minutes after a deploy a reader kept the previous Python package. With the
    hash in the name every deploy is a new URL.
    """
    resources = out / "app.resources.zip"
    worker = out / "app.js"
    page = out / "index.html"
    res_name = f"app.resources.{_short_hash(resources)}.zip"
    js = worker.read_text()
    if "'app.resources.zip'" not in js:
        raise SystemExit("app.js no longer names 'app.resources.zip'; update fingerprint()")
    resources.rename(out / res_name)
    worker.write_text(js.replace("'app.resources.zip'", f"'{res_name}'"))
    js_name = f"app.{_short_hash(worker)}.js"
    worker.rename(out / js_name)
    html = page.read_text()
    if 'new Worker("./app.js")' not in html:
        raise SystemExit("index.html no longer starts ./app.js; update fingerprint()")
    page.write_text(html.replace('new Worker("./app.js")', f'new Worker("./{js_name}")'))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "site")
    args = parser.parse_args()
    out = args.out

    embed_archive()

    build_dir = ROOT / "build" / "static"
    if build_dir.exists():
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True)

    # One script: the data module, then the app with its import removed.
    data_src = (STATIC / "_bundled_data.py").read_text()
    app_src = (STATIC / "app.py").read_text().replace(
        "from _bundled_data import prerelease_zip_bytes\n", ""
    )
    (build_dir / "app.py").write_text(
        "# Generated by static/build.py from static/_bundled_data.py and static/app.py.\n"
        f"{data_src}\n\n{app_src}"
    )

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    wheels = ROOT / "build" / "wheels"
    if wheels.exists():
        shutil.rmtree(wheels)
    subprocess.run(
        [sys.executable, "-m", "pip", "wheel", "--no-deps", "-q", "-w", str(wheels), str(ROOT)],
        check=True,
    )
    wheel = next(wheels.glob("*.whl"))

    subprocess.run(
        [
            sys.executable, "-m", "panel", "convert", str(build_dir / "app.py"),
            "--to", "pyodide-worker", "--out", str(out),
            "--title", "Gaia DR4 Object Explorer",
            "--requirements", *REQUIREMENTS, str(wheel),
        ],
        check=True,
    )
    # GitHub Pages serves index.html; the app itself is the landing page.
    shutil.move(out / "app.html", out / "index.html")
    fingerprint(out)
    (out / ".nojekyll").write_text("")   # keep Pages from filtering files

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"\nbuilt {out} ({total / 1e6:.2f} MB)")
    for f in sorted(out.rglob("*")):
        if f.is_file():
            print(f"  {f.stat().st_size:>9,}  {f.relative_to(out)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
